services:
  postgres:
    image: postgres:15
    container_name: carcodillo_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: carcodillo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: carcodillo_app
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    depends_on:
      - postgres

volumes:
  postgres_data:
